Controllers/ContentAdminController.cs
using Cinema.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;

namespace Cinema.Controllers;
public class ContentAdminController : Controller
{
    private readonly CinemaDBContext _dbContext;
    public ContentAdminController(CinemaDBContext dbContext)
    {
        _dbContext = dbContext;
    }
    public IActionResult Index()
    {
        return View();
    }
    public async Task<IActionResult> ShowAllMovies()
    {
        return View(await _dbContext.Movies.ToListAsync());
    }
    public async Task<IActionResult> ShowScreenings()
    {
        return View(await _dbContext.Screenings.ToListAsync());
    }
    public IActionResult AddNewMovie()
    {
        return View();
    }
    // POST: Movies/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddNewMovie([Bind("Id,Title,Type,Director,Summary,Length")] Movie movie)
    {
        if (ModelState.IsValid)
        {
            _dbContext.Add(movie);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(movie);
    }
    public IActionResult AddNewScreening(int id)
    {
        List<SelectListItem> MovieId = new List<SelectListItem>();
        SelectListItem m = new SelectListItem();
        m.Text = id.ToString();
        m.Value = id.ToString();
        MovieId.Add(m);
        ViewBag.MovieId = MovieId;

        List<SelectListItem> HallId = new List<SelectListItem>();

        foreach(Hall hall in _dbContext.Halls) 
        {
            HallId.Add(new SelectListItem { Text = hall.Id.ToString(), Value = hall.Id.ToString() });
        }

        ViewBag.HallId = HallId;

        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddNewScreening(String MovieId, String HallId, DateTime DatetimeOfPlay)
    {
        int movie_id = int.Parse(MovieId);
        int hall_id = int.Parse(HallId);
        Screening scr = new Screening();
        scr.MovieId = movie_id;
        scr.HallId = hall_id;
        scr.DatetimeOfPlay = DatetimeOfPlay;
        System.Console.WriteLine(ModelState.IsValid.ToString() + scr.MovieId.ToString() + scr.HallId.ToString() + scr.DatetimeOfPlay.ToString());
        if (ModelState.IsValid)
        {
            _dbContext.Add(scr);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(scr);
    }
    // GET: Users/Delete/5
    public async Task<IActionResult> DeleteScreening(int? id)
    {
        if (id == null || _dbContext.Screenings == null)
        {
            return NotFound();
        }

        var scr = await _dbContext.Screenings
            .FirstOrDefaultAsync(m => m.Id == id);
        if (scr == null)
        {
            return NotFound();
        }

        return View(scr);
    }

    // POST: Users/Delete/5
    [HttpPost, ActionName("DeleteScreening")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_dbContext.Screenings == null)
        {
            return Problem("Entity set 'CinemaDBContext.Screenings'  is null.");
        }
        var scr = await _dbContext.Screenings.FindAsync(id);
        if (scr != null)
        {
            _dbContext.Screenings.Remove(scr);
        }

        await _dbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    // GET: Screenings/Edit/5
    public async Task<IActionResult> EditScreening(int? id)
    {
        if (id == null || _dbContext.Screenings == null)
        {
            return NotFound();
        }

        var screening = await _dbContext.Screenings.FindAsync(id);
        if (screening == null)
        {
            return NotFound();
        }
        ViewData["HallId"] = new SelectList(_dbContext.Halls, "Id", "Id", screening.HallId);
        ViewData["MovieId"] = new SelectList(_dbContext.Movies, "Id", "Id", screening.MovieId);
        return View(screening);
    }

    // POST: Screenings/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,MovieId,HallId,DatetimeOfPlay")] Screening screening)
    {
        if (id != screening.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _dbContext.Update(screening);
                await _dbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ScreeningExists(screening.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["HallId"] = new SelectList(_dbContext.Halls, "Id", "Id", screening.HallId);
        ViewData["MovieId"] = new SelectList(_dbContext.Movies, "Id", "Id", screening.MovieId);
        return View(screening);
    }
    private bool ScreeningExists(int id)
    {
        return (_dbContext.Screenings?.Any(e => e.Id == id)).GetValueOrDefault();
    }
}

Views/ContentAdmin/AddNewMovie.cshtml
@model Cinema.Models.Movie

@{
    ViewData["Title"] = "AddNewMovie";
}

<h1>Add New Movie</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddNewMovie">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <input asp-for="Summary" class="form-control" />
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Length" class="control-label"></label>
                <input asp-for="Length" class="form-control" />
                <span asp-validation-for="Length" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ShowAllMovies">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ContentAdmin/AddNewScreening.cshtml
@model Cinema.Models.Screening

@{
    ViewData["Title"] = "AddNewScreening";
}

<h1>Add New Screening</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddNewScreening">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                @Html.DropDownListFor(model => model.MovieId, (List<SelectListItem>)ViewBag.MovieId, "")
                @* <select asp-for="MovieId" class ="form-control" asp-items="ViewBag.MovieId"></select> *@
            </div>
            <div class="form-group">
                <label asp-for="HallId" class="control-label"></label>
                @Html.DropDownListFor(model => model.HallId, (List<SelectListItem>)ViewBag.HallId, "")
                @* <select asp-for="HallId" class ="form-control" asp-items="ViewBag.HallId"></select> *@
            </div>
            <div class="form-group">
                <label asp-for="DatetimeOfPlay" class="control-label"></label>
                <input asp-for="DatetimeOfPlay" class="form-control" />
                <span asp-validation-for="DatetimeOfPlay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ShowScreenings">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ContentAdmin/DeleteScreening.cshtml
@model Cinema.Models.Screening

@{
    ViewData["Title"] = "DeleteScreening";
}

<h1>Delete Screening</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Screening</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatetimeOfPlay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatetimeOfPlay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hall)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HallId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MovieId)
        </dd>
    </dl>
    
    <form asp-action="DeleteScreening">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ShowScreenings">Back to List</a>
    </form>
</div>

Views/ContentAdmin/EditScreening.cshtml
@model Cinema.Models.Screening

@{
    ViewData["Title"] = "EditScreening";
}

<h1>Edit Screening</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditScreening">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class="form-control" asp-items="ViewBag.MovieId"></select>
                <span asp-validation-for="MovieId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HallId" class="control-label"></label>
                <select asp-for="HallId" class="form-control" asp-items="ViewBag.HallId"></select>
                <span asp-validation-for="HallId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatetimeOfPlay" class="control-label"></label>
                <input asp-for="DatetimeOfPlay" class="form-control" />
                <span asp-validation-for="DatetimeOfPlay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ShowScreenings">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ContentAdmin/Index.cshtml
@{
    ViewData["Title"] = "Content Admin page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style type="text/css">
    </style>

</head>
<body>
    <h1>Content Admin Menu</h1>
    @using (Html.BeginForm("ShowAllMovies", "ContentAdmin", FormMethod.Get))
    {
        <div>
            <input type="submit" value="All movies" class="btn btn-primary" />
        </div>
    }
    <br />
    @using (Html.BeginForm("ShowScreenings", "ContentAdmin", FormMethod.Get))
    {
        <div>
            <input type="submit" value="Screenings" class="btn btn-primary" />
        </div>
    }
</body>
</html>

Views/ContentAdmin/ShowAllMovies.cshtml
@model IEnumerable<Cinema.Models.Movie>

@{
    ViewData["Title"] = "ShowAllMovies";
}

<style>
    .table thead {
        background: rgba(0,0,0,0.5);
    }

    p, h1 {
        text-align: center;
    }
</style>

<h1>Show All Movies</h1>

<p>
    <a asp-action="AddNewMovie">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Summary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Length)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Summary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Length)
            </td>
            <td>
                <a asp-action="AddNewScreening" asp-route-id="@item.Id">Add Screening</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/ContentAdmin/ShowScreenings.cshtml
@model IEnumerable<Cinema.Models.Screening>

@{
    ViewData["Title"] = "ShowScreenings";
}

<style>
    .table thead {
        background: rgba(0,0,0,0.5);
    }

    p, h1 {
        text-align: center;
    }
</style>
<h1>Show Screenings</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Movie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hall)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatetimeOfPlay)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MovieId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HallId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatetimeOfPlay)
            </td>
            <td>
                <a asp-action="EditScreening" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="DeleteScreening" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>